name: 'Setup PostgreSQL and PostGIS'
description: 'Setup a PostgreSQL database with PostGIS'
author: 'Nyaruka'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  # See https://hub.docker.com/r/postgis/postgis/tags for supported combinations of postgres and postgis
  # and further details on input environment variables
  postgresql version:
    description: 'Version of PostgreSQL to use'
    required: false
    default: '12'
  postgis version:
    description: 'Version of PostGIS to use'
    required: false
    default: 'master'
  postgresql db:
    description: 'Name for the default database that is created'
    required: false
    default: ''
  postgresql user:
    description: 'Create the specified user with superuser power'
    required: false
    default: ''
  postgresql password:
    description: 'Superuser password'
    required: true
    default: ''
  postgresql init scripts:
    description: 'Directory containing DB init scripts'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
